### ISSUE TITLE
Build Docker environment

### ISSUE THREAD

**Issue by wenhaolu93** [devops-s17-payments/payments#2]
**As a** Developer
**I need** the ability to deploy the service in a Docker container
**So that** I have more deployment options than just Cloud Foundry

**Assumptions**
*TBD*

**Acceptance Criteria**
When I issue `docker build -t payments`
A proper Docker image should be built
And when I issue `docker run -d payments`
And I issue `docker ps`
I should see a payment container running

**Comment by odoric27** [comment]
This issue seems like it may overlap a bit with issue #1 
I revised a bit per the professor's example regarding docker deployment. based on this, I think this might be a item for the next sprint

Also - I'm not sure that docker container creates mysql for us, but I also don't know. Either way, I think we're using redis as DB, right?
