### ISSUE TITLE
Brainstorm database interface

### ISSUE THREAD

**Issue by jdgumz** [devops-s17-payments/payments#95]
*As a* payments API developer
*I need* a minimally functional but clearly defined database interface
*So that* I can properly decouple database logic from any other portions of the application

**Assumptions**

* The database methods that we require can be determined from the current informal implementation (i.e., the lines of code that do database stuff but are still part of other methods).

**Acceptance Criteria**
* There is a suitable method name and signature defined for the following operations:
  * `getting payment items` (this would include searching)
  * `deleting/removing payment items`
  * `updating payment items`

**Comment by odoric27** [comment]
picking up where i left off in #88 ...

the functions and their use cases we need to implement should be something like...

* `get_payments(**args)` 
as laid out by jesse in #88 this includes getting queries, listing all, getting payments by {payment_id} and perhaps also {user_id}
* `remove_payments(payment_id)` (which should really just mark the field as removed instead of actually deleting it. this should be added to a payments model class, which is a story unto itself)
* `update_payments(payment_id)` (this should handle PUT and PATCH operations. our actions (set-default and action) will utilize this as well since both should be PATCHes.)
* `create_payments( )`

anything i'm missing. any thoughts, opinions, theories, etc?

**Comment by jdgumz** [comment]
@odoric27 you have the right idea; of course, whatever we decide ultimately might be a little different but that's the gist of it.

**Comment by odoric27** [comment]
been thinking about this one a bit as a tweak the payments model.

given the current setup of child classes deriving from an abstract BasePayment, we need a way to create the correct object specified by the `payment_type`. i thought something like this:

```
create_payment( ):
    data = request.get_json( )
    type = data['payment_type']
    if type == 'credit' or type == 'debit':
        payment = CardPayment( )
    else:
        payment = PaypalPayment( )
    payment.deserialize(data)
    # add to db
    # commit to db
    return make_response(jsonify(payment.serialize()), status.HTTP_201_CREATED)

```

just putting this here to further the brainstorming/discussion, but i'll write up an issue for this one (probably tomorrow)

**Comment by jdgumz** [comment]
Good point @odoric27 - something to keep in mind for the implementation work later.  I thought about adding a payment type parameter but I agree with your pseudocode; it's probably fine to just get the type info from the data dict.
